### ISSUE TITLE
EcoFreq service is inactive

### ISSUE THREAD

**Issue by BenoitMorel** [amkozlov/eco-freq#8]
Hi Alexey,

Here is another issue: I start the service according the wiki, but it doesn't seem to be active.
The installation went smoothly.

```
benoit:~$ sudo systemctl start ecofreq
benoit:~$ ./ecorun.py sleep 5
ERROR: File not found: /dev/shm/ecofreq
Please make sure that EcoFreq service is active!
```

Let me know if I can send your more information

Cheers,
Benoit

**Comment by amkozlov** [comment]
You can always check if ecofreq service is running, and if not why, using the following command:

`systemctl status ecofreq`

In this case, location autodetection failed, maybe because internet connection was unavailable. It is probably more reliable to specify country code manually in the `ecofreq.cfg` file, eg

```
[co2signal]
Country=DE
```

**Comment by BenoitMorel** [comment]
Specifying `Country=DE` made it work, thanks!
